baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "BakedNFT | Web3 Agency | NFT Marketing Studio"

[params]
description = "Baked is an independent creative studio working with some of the world’s biggest brands. We launch NFT projects that build brand value."
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]